### ISSUE TITLE
Packaged the program for AUR

### ISSUE THREAD

**Issue by JinEnMok** [wintermute-cell/ngrrram#5]
Hello there! 

Kudos for the cool program, especially the free cat. I've uploaded a simple PKGBUILD to AUR,for both a [git build](https://aur.archlinux.org/packages/ngrrram-git) and a [binary version](https://aur.archlinux.org/packages/ngrrram-bin). Should be accessible to Arch users now.

I'm not too sure on the licence, though - is it GPLv3 only or GPLv3 or later?

**Comment by wintermute-cell** [comment]
v3 only is fine! Thanks a lot!
